[[language]]
name = "svelte"
# formatter = { command = "biome", args = [
# "format",
# "--stdin-file-path=a.svelte",
# ] }
formatter = { command = "deno", args = [
  "fmt",
  "--unstable-component",
  "--ext",
  "svelte",
  "-",
] }
language-servers = [
  "tailwindcss-language-server",
  "svelteserver",
  "typescript-language-server",
]
